CREATE TABLE IF NOT EXISTS users (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username         VARCHAR(50)  NOT NULL UNIQUE,
    email            VARCHAR(255) NOT NULL UNIQUE,
    password_hash    VARCHAR(255) NOT NULL,
    created_at       TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    failed_attempts  INT          DEFAULT 0,
    locked_until     TIMESTAMP    NULL
);

CREATE TABLE IF NOT EXISTS audit_log (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_time TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    action     VARCHAR(50) NOT NULL,
    username   VARCHAR(50),
    source_ip  VARCHAR(45),
    outcome    VARCHAR(10) NOT NULL,
    details    VARCHAR(500)
);
